import math
a = float(input("masukkan angka A="))
b = float(input("masukkan angka B="))
print("hasil penjumlahan=", a+b)
print("hasil pengurangan=", a-b)
print("hasil perkalian=", a*b)
print("hasil sisa pembagian=", a%b)
print("hasil pembagian=", a/b)
print("hasil pemangkatan=", a**b)
print("hasil logaritma=", math.log10(a))
